
#Utworzenie admina bazy danych
CREATE USER 'admin'@'%' IDENTIFIED BY '***';GRANT USAGE ON *.* TO 'admin'@'%' IDENTIFIED BY '***' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;GRANT ALL PRIVILEGES ON `kuriex`.* TO 'admin'@'%';